### ISSUE TITLE
customize image size

### ISSUE THREAD

**Issue by jenshweber** [carocad/nerdy-painter#1]
Hello,
thanks for this great plugin.
I am wondering if there is a way to increase / customize the allowable image size. The images seem to be clipped at a fixed size currently.
Thanks
Jens

**Comment by carocad** [comment]
Hey Jens,
which version are you using? until v0.0.2 the images sized were fixed due to the inline-results of lighttable. That is no longer a problem in v0.0.3 since the images are displayed underline.

BTW: are you using your own middleware or is it with incanter? if it is so then you should adjust the function to get the size that you want; the default is 400x300 pixels (see relevant lines below).

```
width     (or (:width opts) 400)
height    (or (:height opts) 300)
```

**Comment by jenshweber** [comment]
Thanks so much for the response. Yes, I updated to v0.0.3 prior to writing this message. However, I failed to restart LightTable. After restarting LightTable everything works great. Thanks again!
